# Site settings
name: May Pongpitpitak
title: May Pongpitpitak
description: "May's Personal Page"
url: "www.mayppong.com"

# Build settings
markdown: kramdown
permalink: pretty
sass:
  style: compressed

plugins:
  - jekyll-archives
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
      
exclude: ["CNAME", "sitemap.xml", "feed.xml", "LICENSE", "README.md"]

##
# ATOM feed
author:
  name: May Pongpitpitak

##
# Jekyll archive gem for /tags/ page
jekyll-archives:
  enabled:
    - tags